// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNYCbIwEsqfSCn5NmwRKdVRzOsphZ25V4',
    appId: '1:593965927948:web:e548d06652455e63d2e829',
    messagingSenderId: '593965927948',
    projectId: 'authtutorial-2e792',
    authDomain: 'authtutorial-2e792.firebaseapp.com',
    storageBucket: 'authtutorial-2e792.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBErGm0WisNB5oge-FPSdMMQggr73gewCE',
    appId: '1:593965927948:android:3807e56df2c0a548d2e829',
    messagingSenderId: '593965927948',
    projectId: 'authtutorial-2e792',
    storageBucket: 'authtutorial-2e792.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr7u2D0KUd44bEbbDgSNkKKZtH14I9EA4',
    appId: '1:593965927948:ios:9cdc0b63c7e36697d2e829',
    messagingSenderId: '593965927948',
    projectId: 'authtutorial-2e792',
    storageBucket: 'authtutorial-2e792.appspot.com',
    iosClientId: '593965927948-tarra77e8gb61rt4knrbruk7e9le26q0.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr7u2D0KUd44bEbbDgSNkKKZtH14I9EA4',
    appId: '1:593965927948:ios:9cdc0b63c7e36697d2e829',
    messagingSenderId: '593965927948',
    projectId: 'authtutorial-2e792',
    storageBucket: 'authtutorial-2e792.appspot.com',
    iosClientId: '593965927948-tarra77e8gb61rt4knrbruk7e9le26q0.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignmentApp',
  );
}
